### ISSUE TITLE
Crashes akka build over documentation step

### ISSUE THREAD

**Issue by matanox** [CANVE/extractor#10]
Running canve for Akka 2.4.1:

```
[info] Main Scala API documentation successful.
[trace] Stack trace suppressed: run last akka-persistence/compile:doc for the full output.
[trace] Stack trace suppressed: run last akka-slf4j/compile:doc for the full output.
[trace] Stack trace suppressed: run last akka-osgi/compile:doc for the full output.
[trace] Stack trace suppressed: run last akka-cluster/compile:doc for the full output.
[trace] Stack trace suppressed: run last akka-remote/compile:doc for the full output.
[trace] Stack trace suppressed: run last akka-testkit/compile:doc for the full output.
[trace] Stack trace suppressed: run last akka-actor/compile:doc for the full output.
[error] (akka-persistence/compile:doc) ScalaDoc diagrams not generated!
[error] (akka-slf4j/compile:doc) ScalaDoc diagrams not generated!
[error] (akka-osgi/compile:doc) ScalaDoc diagrams not generated!
[error] (akka-cluster/compile:doc) ScalaDoc diagrams not generated!
[error] (akka-remote/compile:doc) ScalaDoc diagrams not generated!
[error] (akka-testkit/compile:doc) ScalaDoc diagrams not generated!
[error] (akka-actor/compile:doc) ScalaDoc diagrams not generated!
canve task aborted as it could not successfully compile the project (or due to its own internal error)
```

And the full exception from the full output:

```
java.lang.RuntimeException: ScalaDoc diagrams not generated!
    at scala.sys.package$.error(package.scala:27)
    at akka.Scaladoc$.scaladocVerifier(Doc.scala:72)
    at akka.Scaladoc$$anonfun$projectSettings$5$$anonfun$apply$1.apply(Doc.scala:34)
    at akka.Scaladoc$$anonfun$projectSettings$5$$anonfun$apply$1.apply(Doc.scala:31)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[error] (akka-persistence/compile:doc) ScalaDoc diagrams not generated!
```

This does not happen on `clean` then `compile` or on `test:compile`, only when running the `canve` command in sbt. 

The error comes from [here in akka's code](https://github.com/akka/akka/blob/dc12f3bfd339ac1ad4407bdc1f01d6a418f5f339/project/Doc.scala#L70-L72)

**Comment by matanox** [comment]
Akka doc step requires java 8 jdk, and also solved by https://github.com/CANVE/integration-test-projects/commit/dde2824f371730363fc8f10a5200e5c425351c8a
